name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_validate:
    name: Lint & validate (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install TeX Live (for biber validation)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-bibtex-extra biber

      - name: Install project and dependencies
        run: uv sync --dev
        # UV automatically creates venv and installs all dependencies

      - name: Create generated directory
        run: mkdir -p bib/generated

      - name: Run all validations (pre-commit)
        run: uv run pre-commit run --all-files
        # Runs all hooks: ruff, pyright, jsonschema, custom validation, biber validation, etc.

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [lint_and_validate]
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install project (dev)
        run: uv sync --dev

      - name: Run pytest (if tests/ exists)
        if: ${{ hashFiles('tests/**') != '' }}
        run: uv run pytest -q
