name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_validate:
    name: Lint & schema checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project and dependencies
        run: uv sync --dev
        # UV automatically creates venv and installs all dependencies

      - name: Run pre-commit (all hooks)
        run: uv run pre-commit run --all-files
        # Use UV to run pre-commit with proper environment

      - name: Extra JSON Schema validation (explicit)
        run: |
          uv run check-jsonschema --schemafile data/identifier_collection.schema.json \
                                  data/identifier_collection.json
        # CLI usage: --schemafile <schema> <instances...>

      - name: Custom validation (citekey consistency & labels)
        run: uv run python -m biblib.cli validate
        # Validates that citekeys are consistent across all files and match generated labels

      - name: Type check (pyright)
        run: uv run pyright

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [lint_and_validate]
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project (dev)
        run: uv sync --dev

      - name: Run pytest (if tests/ exists)
        if: ${{ hashFiles('tests/**') != '' }}
        run: uv run pytest -q

  biber_validation:
    name: Validate .bib with biber
    runs-on: ubuntu-latest
    needs: [lint_and_validate]
    steps:
      - uses: actions/checkout@v4

      - name: Install TeX Live (biber)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-bibtex-extra biber

      - name: Create generated directory
        run: mkdir -p bib/generated

      - name: Validate library.bib with biber --tool
        run: |
          biber --tool --validate-datamodel --output-directory bib/generated bib/library.bib
        # Direct validation of .bib file integrity without LaTeX compilation
